// CivicPulse AI - Initial In-Memory Seed Dataset
// Pre-configured municipal wards, users, complaints, and audit logs

import { Ward, Profile, Complaint, ComplaintAuditLog } from "@/types/database";

export const INITIAL_WARDS: Ward[] = [
  {
    id: "WARD_14",
    name: "Ward 14 • Civil Lines",
    zone: "Central Zone",
    center: [26.9124, 75.7891],
    description: "Administrative & VIP corridor, high-traffic arterial intersections.",
    boundary: [
      [
        [75.775, 26.900],
        [75.805, 26.900],
        [75.805, 26.925],
        [75.775, 26.925],
        [75.775, 26.900],
      ],
    ],
  },
  {
    id: "WARD_15",
    name: "Ward 15 • Mansarovar",
    zone: "South Zone",
    center: [26.8582, 75.7654],
    description: "Dense residential colony, parks, and institutional hubs.",
    boundary: [
      [
        [75.745, 26.840],
        [75.785, 26.840],
        [75.785, 26.875],
        [75.745, 26.875],
        [75.745, 26.840],
      ],
    ],
  },
  {
    id: "WARD_16",
    name: "Ward 16 • Vaishali Nagar",
    zone: "West Zone",
    center: [26.9110, 75.7420],
    description: "Rapid commercial and residential developments, Queens Road corridor.",
    boundary: [
      [
        [75.720, 26.890],
        [75.760, 26.890],
        [75.760, 26.930],
        [75.720, 26.930],
        [75.720, 26.890],
      ],
    ],
  },
  {
    id: "WARD_17",
    name: "Ward 17 • C-Scheme",
    zone: "Central Zone",
    center: [26.9184, 75.8112],
    description: "High-density commercial markets, MI Road retail strip.",
    boundary: [
      [
        [75.795, 26.905],
        [75.825, 26.905],
        [75.825, 26.935],
        [75.795, 26.935],
        [75.795, 26.905],
      ],
    ],
  },
];

export const INITIAL_PROFILES: Profile[] = [
  {
    id: "user-crew-1",
    full_name: "Ramesh Kumar",
    phone: "+91 98290 23456",
    role: "FIELD_CREW",
    ward_id: "WARD_14",
    is_active: true,
    department: "Roads & Civil Infrastructure",
    active_tasks_count: 2,
  },
  {
    id: "user-crew-2",
    full_name: "Mohan Lal",
    phone: "+91 98290 34567",
    role: "FIELD_CREW",
    ward_id: "WARD_15",
    is_active: true,
    department: "Sanitation & Solid Waste",
    active_tasks_count: 1,
  },
  {
    id: "user-crew-3",
    full_name: "Vikram Meena",
    phone: "+91 98290 77777",
    role: "FIELD_CREW",
    ward_id: "WARD_16",
    is_active: true,
    department: "Electrical & Street Lighting",
    active_tasks_count: 0,
  },
  {
    id: "user-supervisor-1",
    full_name: "Er. Anita Verma",
    phone: "+91 98290 45678",
    role: "WARD_SUPERVISOR",
    ward_id: "WARD_14",
    is_active: true,
    department: "Ward 14 Operations",
  },
  {
    id: "user-supervisor-2",
    full_name: "Er. Suresh Gupta",
    phone: "+91 98290 56789",
    role: "WARD_SUPERVISOR",
    ward_id: "WARD_15",
    is_active: true,
    department: "Ward 15 Operations",
  },
  {
    id: "user-commissioner",
    full_name: "Dr. Rajesh Meena, IAS",
    phone: "+91 98290 99999",
    role: "MUNICIPAL_COMMISSIONER",
    is_active: true,
    department: "Executive Municipal Governance",
  },
];

const now = new Date();

export const INITIAL_COMPLAINTS: Complaint[] = [
  {
    id: "ticket-001",
    citizen_id: "public-intake",
    title: "Deep crater pothole near Railway Crossing",
    description: "Dangerous pothole approximately 1.5ft deep on main corridor causing severe traffic crawl and two-wheeler skids.",
    category: "POTHOLE",
    status: "PENDING",
    latitude: 26.912440,
    longitude: 75.789120,
    address_text: "Hawa Sadak near Railway Crossing, Civil Lines",
    ward_id: "WARD_14",
    image_url: "https://images.unsplash.com/photo-1515162816999-a0c47dc192f7?w=800&q=80",
    upvotes_count: 5,
    sla_deadline: new Date(now.getTime() + 32 * 3600000).toISOString(),
    created_at: new Date(now.getTime() - 16 * 3600000).toISOString(),
    updated_at: new Date(now.getTime() - 16 * 3600000).toISOString(),
  },
  {
    id: "ticket-002",
    citizen_id: "public-intake",
    title: "Overflowing municipal garbage container",
    description: "Garbage spilled across pavement blocking pedestrian walkway and emitting foul odor outside public park.",
    category: "GARBAGE",
    status: "ASSIGNED",
    latitude: 26.858200,
    longitude: 75.765400,
    address_text: "Sector 3 Circle, Mansarovar",
    ward_id: "WARD_15",
    image_url: "https://images.unsplash.com/photo-1611284446314-60a58ac0deb9?w=800&q=80",
    upvotes_count: 2,
    assigned_crew_id: "user-crew-2",
    supervisor_id: "user-supervisor-2",
    sla_deadline: new Date(now.getTime() + 10 * 3600000).toISOString(),
    created_at: new Date(now.getTime() - 14 * 3600000).toISOString(),
    updated_at: new Date(now.getTime() - 10 * 3600000).toISOString(),
  },
  {
    id: "ticket-003",
    citizen_id: "public-intake",
    title: "Non-functioning high-mast streetlight pole",
    description: "3 luminaire units unlit for past 4 nights creating dark hazard zone for evening pedestrians and women's safety.",
    category: "STREETLIGHT",
    status: "WORK_SUBMITTED",
    latitude: 26.911020,
    longitude: 75.742010,
    address_text: "Queen's Road, Vaishali Nagar",
    ward_id: "WARD_16",
    image_url: "https://images.unsplash.com/photo-1509114397022-ed747cca3f65?w=800&q=80",
    upvotes_count: 4,
    assigned_crew_id: "user-crew-1",
    supervisor_id: "user-supervisor-1",
    resolution_image_url: "https://images.unsplash.com/photo-1517420704952-d9f39e95b43e?w=800&q=80",
    resolution_latitude: 26.911026,
    resolution_longitude: 75.742018,
    resolution_distance_meters: 1.2,
    resolution_submitted_at: new Date(now.getTime() - 2 * 3600000).toISOString(),
    sla_deadline: new Date(now.getTime() + 26 * 3600000).toISOString(),
    created_at: new Date(now.getTime() - 22 * 3600000).toISOString(),
    updated_at: new Date(now.getTime() - 2 * 3600000).toISOString(),
  },
  {
    id: "ticket-004",
    citizen_id: "public-intake",
    title: "Potable water pipeline rupture on service lane",
    description: "Fresh drinking water gushing onto the road causing road collapse risk and low tap pressure across Ward 14.",
    category: "WATER_LEAK",
    status: "RESOLVED",
    latitude: 26.915000,
    longitude: 75.792500,
    address_text: "Near Tonk Phatak underpass, Civil Lines",
    ward_id: "WARD_14",
    image_url: "https://images.unsplash.com/photo-1584824486509-112e4181ff6b?w=800&q=80",
    upvotes_count: 8,
    assigned_crew_id: "user-crew-1",
    supervisor_id: "user-supervisor-1",
    resolution_image_url: "https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=800&q=80",
    resolution_latitude: 26.915004,
    resolution_longitude: 75.792505,
    resolution_distance_meters: 0.7,
    resolution_submitted_at: new Date(now.getTime() - 8 * 3600000).toISOString(),
    supervisor_notes: "Inspected on-site. Pipeline clamped, pressure tested to 4.5 bar, asphalt patch restored level.",
    verified_at: new Date(now.getTime() - 6 * 3600000).toISOString(),
    reopen_window_closes_at: new Date(now.getTime() + 42 * 3600000).toISOString(), // 48h audit window
    sla_deadline: new Date(now.getTime() + 18 * 3600000).toISOString(),
    created_at: new Date(now.getTime() - 30 * 3600000).toISOString(),
    updated_at: new Date(now.getTime() - 6 * 3600000).toISOString(),
  },
  {
    id: "ticket-005",
    citizen_id: "public-intake",
    title: "Collapsed concrete drain slab on footpath",
    description: "Hazardous open chasm 6 feet deep where reinforced slab crumbled. Severe public risk at night.",
    category: "OTHER",
    status: "ESCALATED",
    latitude: 26.918400,
    longitude: 75.811200,
    address_text: "MI Road Commercial Walkway, C-Scheme",
    ward_id: "WARD_17",
    image_url: "https://images.unsplash.com/photo-1541888946425-d0fbb186f5f7?w=800&q=80",
    upvotes_count: 14,
    sla_deadline: new Date(now.getTime() - 6 * 3600000).toISOString(), // Breached
    created_at: new Date(now.getTime() - 54 * 3600000).toISOString(),
    updated_at: new Date(now.getTime() - 6 * 3600000).toISOString(),
  },
];

export const INITIAL_AUDIT_LOGS: ComplaintAuditLog[] = [
  {
    id: "audit-001",
    complaint_id: "ticket-004",
    actor_name: "Er. Anita Verma",
    action: "RESOLVED",
    from_status: "WORK_SUBMITTED",
    to_status: "RESOLVED",
    remarks: "Visual proof verified. Delta 0.7m within compliance tolerance.",
    created_at: new Date(now.getTime() - 6 * 3600000).toISOString(),
  },
  {
    id: "audit-002",
    complaint_id: "ticket-003",
    actor_name: "Ramesh Kumar",
    action: "WORK_SUBMITTED",
    from_status: "ASSIGNED",
    to_status: "WORK_SUBMITTED",
    remarks: "Repaired luminaire wiring. Live photo stamped at site.",
    created_at: new Date(now.getTime() - 2 * 3600000).toISOString(),
  },
  {
    id: "audit-003",
    complaint_id: "ticket-005",
    actor_name: "System SLA Engine",
    action: "ESCALATED",
    from_status: "PENDING",
    to_status: "ESCALATED",
    remarks: "Unassigned past 12h threshold. Category SLA (48h) exceeded.",
    created_at: new Date(now.getTime() - 6 * 3600000).toISOString(),
  },
];
